os:
  - linux
  - osx
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
sudo: false
install:
  # Ensure source install works and compiles correctly
  - npm install
  # test our module
  - UBS_OPTS="-D" ./bin/ubs test
after_success:
