language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.4"
  - "5.11"
  - "6.2"
sudo: false
install:
  # Ensure source install works and compiles correctly
  - npm install
  # test our module
  - UBS_OPTS="-D" npm test
after_success:
