init:
  plugins:
    - mocha
    - packagejson
    - clean
settings:
  toClean: ['lib', 'build']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    bin: 'mocha'
    useCoffee: true
prebuild:
  - npm update
build:
  - echo Building %name version %version ...
  - coffee -o %libPath -c %srcPath/*.coffee
test:
  - task: build
  - task: mocha-test
install:
  - task: build
  - echo Moving plugins to lib/plugins folder
  - mkdir %libPath/plugins
  - cp %srcPath/plugins/* %libPath/plugins/
  - echo Installation complete, you can 'cd %libPath'
