# The init part, checked first and looks for plugins to load (in order, but order
# in this example does not really matter).
init:
  plugins:
    - mocha
    - packagejson
    - clean
# It is the place to set environment variables. Plugins can add extra key=value
# settings, as for Mocha where 'bin' and 'useCoffe'. Mocha options are modified
# by useCoffee then propagated when called.
# We tell 'clean' package to not remove 'lib' globally but only the core build.
# This allows plugins to remain intact for next build.
settings:
  cleanPath: ['lib/*.js']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    bin: 'mocha'
    useCoffee: true
prebuild:
  - npm update
# Note that you can call shell commands
# %name and %version are variables from settings above. They are string replaced
# before running command.
build:
  - echo Building %name version %version ...
  - coffee -o %libPath -c %srcPath/*.coffee
# Sometimes you rely on other tasks, so that is the way you call them.
# Here mocha-test is a rule created by the 'mocha' plugin
test:
  - task: install
  - task: mocha-test
# Splitted install and install_plugins because building UBS requires these plugins
# to be installed first hand. This build.yml needs them in their expected places.
install:
  - task: install_plugins
  - task: build
install_plugins:
  - echo Moving plugins to lib/plugins folder
  - mkdir -p %libPath/plugins
  - cp -f %srcPath/plugins/* %libPath/plugins/
  - echo Installation complete, you can 'cd %libPath'
