# The init part is run first. It looks for plugins to load (in order, but order
# in this example does not really matter).
init:
  plugins:
    - mocha
    - packagejson
    - clean
# It is the place to set plugins variables. Plugins can add extra key=value
# settings, as for Mocha where 'bin' and 'useCoffee'. Mocha options are modified
# accordingly. The special 'env' can be overridden to add new environment variables.
# We tell 'clean' package to remove 'lib' globally. We need to rebuild all each time.
settings:
  toClean: ['lib/']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    bin: './node_modules/.bin/mocha'
    useCoffee: true
# You can call shell commands as well. In the build task, %name and %version are
# variables from settings above. They are replaced in place before running command.
build:
  - echo Building %name version %version ...
  - coffee -b -c -o %libPath %srcPath/
# Sometimes you rely on other tasks, so that is the way you call them.
# Here mocha-test is a rule created by the 'mocha' plugin
test:
  - echo Running test suites...
  - task: mocha-test
# Splitted install and install_plugins because building UBS requires these plugins
# to be installed first hand. This build.yml needs them in their expected places.
install:
  - task: build
  - task: install_plugins
install_plugins:
  - echo Copying YAML plugins to lib/plugins folder
  - cp -f %srcPath/plugins/*.yaml %libPath/plugins/
  - echo Copying JS plugins to lib/plugins folder
  - cp -f %srcPath/plugins/*.js %libPath/plugins/
