init:
  plugins:
    - mocha
    - packagejson
    - clean
settings:
  pluginPath: './src/plugins'
  toClean: ['lib', 'build']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    bin: 'mocha'
    useCoffee: true
prebuild:
  - npm update
build:
  - echo Building %name version %version ...
  - coffee -o %libPath -c %srcPath
test:
  - task: build
  - task: mocha-test
install:
  - task: test
  - echo Installation complete, you can 'cd %libPath'
